### ISSUE TITLE
Mobile-end not detecting some controls

### ISSUE THREAD

**Issue by tyb51** [helloparthshah/StadiaWireless#12]
**Describe the bug**
On my mobile end the directional pad, joysticks and the left and right triggers are not detecting any input and thus not sending any data to the desktop server. I know the controller is working because moving the joystick up and down causes the browser window on my phone move up and down, but the webapp doesn't seem to catch any of that.

**To Reproduce**
1. Open Stadia Wireless on desktop
2. Open webbrowser on mobile
3. Connect controller (which gets detected) on mobile
4. Use controller. Confirm inputs on both mobile and desktop webserver

**Expected behavior**
Full transmission of controls to desktop.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 pro
 - OS: Android 11
 - Browser Vivaldi, Chrome,...
 - Version latest

**Additional context**

**Comment by helloparthshah** [comment]
Can you try opening https://gamepad-tester.com/ and see if you have the same problem with that too

**Comment by tyb51** [comment]
Yes, I already have. Same result.
I was thinking it might be related to the non binary input value of the joystick an trigger? (Doesn't explain the directional pad tho...)

**Comment by helloparthshah** [comment]
Can you attach the logs by clicking the bottom right icon that looks like a gear.

**Comment by tyb51** [comment]
![Screenshot_2022-07-12-21-46-47-00_d365b52accad0f47adbc08c16219827d](https://user-images.githubusercontent.com/27013075/178581245-4920dca5-da14-49d5-9668-816b93d6832c.jpg)

**Comment by helloparthshah** [comment]
I have no way of testing this but it might be related to how your device interfaces with the controller. Instead of letting the webpage access the controller the os might be capturing it
