### ISSUE TITLE
Virus and where to find msi?

### ISSUE THREAD

**Issue by Blodskjegg** [helloparthshah/StadiaWireless#13]
First, my antivirus keeps deleting server.exe, so I cant use it.
Second, I cant find the msi install file you mention in the description

**Comment by helloparthshah** [comment]
It seems like some antiviruses flag python executables created using pyinstaller as viruses. According to this https://stackoverflow.com/questions/55907339/how-to-prevent-exe-created-by-pyinstaller-from-being-deleted-by-antivirus seems like a lot of people have issues with false positives. You could try overriding or whitelisting this specific file in your antivirus settings or running the python script by cloning the git repo.
Sorry but I forgot to update the description but the latest version no longer includes an installer.

**Comment by Blodskjegg** [comment]
Ok, thanks I will try that.
