### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by Reoverv** [helloparthshah/StadiaWireless#14]
**Describe the bug**
I cant accsess the local server (both the ip and computer name) 
The ip adress does take some time to load 
The computer name instantly says "Site unreachable"

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - using Ethernet (dont know if this makes a difference) 

**Smartphone (please complete the following information):**
 - OnePlus 7T
 - Android 11
 - Chrome

**Comment by helloparthshah** [comment]
There is an issue where the IP given isn't the correct interface. You can try using ipconfig and find the IP for your interface (Should be Wireless LAN Adapter I think).
