### ISSUE TITLE
No Controller Connected

### ISSUE THREAD

**Issue by UziTech** [helloparthshah/StadiaWireless#16]
**Describe the bug**
The website says "No Controller Connected" when the controller is connected to the phone. Am I missing a step?

**To Reproduce**
1. Install StadiaWireless
2. Connect controller to stadia app on phone
3. Open webpage on phone

**Expected behavior**
Controller connected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 1.2.0

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13
 - Browser Chrome
 - Version 1.2.0

**Comment by helloparthshah** [comment]
Is the controller visible on your phone when you open https://gamepad-tester.com/

**Comment by UziTech** [comment]
I got it to work by disconnecting the controller from the stadia app and just connecting through usb
