### ISSUE TITLE
[Suggestion] Make instructions clearer or set up an installer?

### ISSUE THREAD

**Issue by ELowry** [helloparthshah/StadiaWireless#2]
The current instructions are written for people who can intuitively figure out that Python must be installed; how to use pip, and much more. This is fine for an early release; but will make it nearly impossible to understand for a vast majority of people.

I would recommend one of two solutions:

1. Set up real step-by-step instructions (including installing Python with environment variables so that the pip command can run anywhere).
2. Find a way to create some sort of installer/executable so that users can run the entire script without the need for a terminal.

**Comment by helloparthshah** [comment]
Yes I'm planning on creating a detailed tutorial as well as some sort of application/installer later when I have time

**Comment by helloparthshah** [comment]
Latest release now includes a installer as well as a standalone pre-installed exe
