### ISSUE TITLE
Error running server.exe

### ISSUE THREAD

**Issue by AureliusAce** [helloparthshah/StadiaWireless#20]
Hi, I'm sorry if I'm wrong here with my request. I installed Python 3.9. If I do try to run the server.exe i get an "Unhandeled exception in script"-Error. It says "Failed to execute script 'serve' due to unhandeled exception: VIGEM_ERROR_BUS_NOT_FOUND" It happens when I start the .exe from the zip folder And also if I unpack the ZIP folder beforehand and then want to start the file. Can someone help me? Thank you and best regards

**Comment by helloparthshah** [comment]
As the FAQ specifies, you could try installing vgamepad by executing pip install vgamepad If that still doesn't work then try installing https://vigem.org/Downloads/
