### ISSUE TITLE
JoyToKey keeps detecting as different controllers

### ISSUE THREAD

**Issue by shmuelsash** [helloparthshah/StadiaWireless#24]
**Describe the bug**
I'm using JoyToKey to remap the inputs of the controller but each time I connect it it comes up as a different controller in JoyToKey and I need remap all the keys again

**Expected behavior**
Each time I connect the controller JoyToKey should detect it as the same controller

**Screenshots**
This is what I mean by different controllers. The first time it came up as Joystick 3 then as Joystick 2
![image](https://user-images.githubusercontent.com/35056305/206706672-d8ef20cd-a27c-4560-869a-2feaf8e85ee9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108.0.5359.71

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android 12
 - Browser Chrome
 - Version 108.0.5359.79

**Comment by helloparthshah** [comment]
Currently, with how the controller is emulated, it creates a new device every time. I can try looking into it but I don't think I would be able to fix this.

**Comment by shmuelsash** [comment]
Ok thanks!
