### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by flayman** [helloparthshah/StadiaWireless#26]
I've tried to make a distribution using pyinstaller, but I can't get it working. I wanted to set the port number for the server. Could you please explain how making a binary release works? Alternatively, it would be nice if the port number was configurable instead of random.

**Comment by helloparthshah** [comment]
I used [Auto PY to EXE](https://pypi.org/project/auto-py-to-exe/) to generate the release you'll need to add the static, templates and vgamepad folders as additional folders. 
![image](https://user-images.githubusercontent.com/35399171/211221623-846c772a-0a5d-43d6-8144-2f137f492cc4.png)
The command it generated is ```pyinstaller --noconfirm --onedir --windowed --icon "D:/Projects/pythonProjects/StadiaWireless/logo.ico" --add-data "D:/Projects/pythonProjects/StadiaWireless/static;static/" --add-data "D:/Projects/pythonProjects/StadiaWireless/templates;templates/" --add-data "D:/Projects/pythonProjects/StadiaWireless/vgamepad;vgamepad/"  "D:/Projects/pythonProjects/StadiaWireless/server.py"```

**Comment by flayman** [comment]
Thank you. This is very good information. Might I suggest you make this part of the documentation?

**Comment by helloparthshah** [comment]
Updated the readme to include the pyinstaller commands
