### ISSUE TITLE
Stadia Bluetooth mode

### ISSUE THREAD

**Issue by naxey** [helloparthshah/StadiaWireless#28]
I understand this has nothing to do with the repo itself. However, I think that users searching for a solution might be interested in a completely wireless solution and should be made aware of the existence of this first-party feature https://stadia.google.com/controller/.
You might want to put this somewhere into the read me

**Comment by helloparthshah** [comment]
Added information about the Stadia Shutdown and link to the Bluetooth tool in the readme https://github.com/helloparthshah/StadiaWireless/commit/1161ccc4eac291c18c2ffa572db6f6d6b5229466
