### ISSUE TITLE
[Optimization] Remove/Disable eruda by default in the release package

### ISSUE THREAD

**Issue by ELowry** [helloparthshah/StadiaWireless#7]
**Describe the bug**
Currently, the release version includes the `eruda` console.
This is great for development and testing purposes, but adds a rather large JavaScript package to the client web page.
As the system matures and becomes more reliable, it may be a good idea to remove this package by default.

**To Reproduce**
_N/A_

**Expected behavior**
Ideally, one of two solutions could be applied:
1. The `eruda` script is not included in the release package at all; and is only included when deploying the project manually.
2. The `eruda` script is only loaded if some parameter is set by the user. For example, this could require to add a `console.js` file to the `StadiaWireless/static/` folder which sets a variable to true; only then would the script be loaded.

**Screenshots**
_N/A_

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.169
 - Browser: Firefox
 - Version: 102.0.1

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: Android 11 (MIUI Global 12.5.8)
 - Browser: Firefox
 - Version: 102.2.0

**Additional context**
One element to keep in mind is that including external scripts from CDNs can technically lead to some forms of tracking and increase the risk of malicious code. **Since the whole project is locally self-hosted, it may be best to avoid loading any external assets entirely.**

**Comment by helloparthshah** [comment]
I think removing eruda in the release would be the best solution although the source code could benefit from keeping it for debugging
