### ISSUE TITLE
[Bug] The wrong IP is displayed

### ISSUE THREAD

**Issue by ELowry** [helloparthshah/StadiaWireless#8]
**Describe the bug**
The IP address displayed in the system tray (right-click on the icon) is technically a functional local IP; but is not publicly available over LAN.
Specifically, in my case, the IP that gets displayed is `192.168.137.1` whereas my device's actual IP on the local network is `192.168.1.69`.

**To Reproduce**
_N/A_

**Expected behavior**
I am unsure of this; but it looks like only the adapter with DHCP should be considered in the case where there are multiple ones available?

**Screenshots**
![image](https://user-images.githubusercontent.com/7792033/178142740-d7fe55f5-325d-4b7e-958e-446d2dccb8a7.png)

Running the `ipconfig /all` command in PowerShell returns the following (redacted for obvious reasons):
```
Wireless LAN adapter Local Area Connection* 10:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : [REDACTED]
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : [REDACTED]
   IPv4 Address. . . . . . . . . . . : 192.168.137.1(Preferred)
   Subnet Mask . . . . . . . . . . . : [REDACTED]
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : ASUS PCE-AC68 802.11ac Network Adapter
   Physical Address. . . . . . . . . : [REDACTED]
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Temporary IPv6 Address. . . . . . : [REDACTED]
   Link-local IPv6 Address . . . . . : [REDACTED]
   IPv4 Address. . . . . . . . . . . : 192.168.1.69(Preferred)
   Subnet Mask . . . . . . . . . . . : [REDACTED]
   Lease Obtained. . . . . . . . . . : [REDACTED]
   Lease Expires . . . . . . . . . . : [REDACTED]
   Default Gateway . . . . . . . . . : [REDACTED]
   DHCP Server . . . . . . . . . . . : [REDACTED]
   DHCPv6 IAID . . . . . . . . . . . : [REDACTED]
   DHCPv6 Client DUID. . . . . . . . : [REDACTED]
   DNS Servers . . . . . . . . . . . : [REDACTED]
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.169
 - Browser: Firefox
 - Version: 102.0.1

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: Android 11 (MIUI Global 12.5.8)
 - Browser: Firefox
 - Version: 102.2.0

**Additional context**
My motherboard does not include a wireless adapter and there is no Ethernet cable connected, so the ASUS PCI-Express adapter is the only running network device.

**Comment by helloparthshah** [comment]
The 2 addresses displayed are the hostname and the IP address of the hostname the server is on. I was having issues similar to you where I couldn't access the website due to the local IP not being exposed and thus included the hostname form, which technically should be exposed on LAN. If you're still having issues then there might be something going on with your firewall.
