### ISSUE TITLE
[Feature Request] Set up a host-side input display/checker.

### ISSUE THREAD

**Issue by ELowry** [helloparthshah/StadiaWireless#9]
**Is your feature request related to a problem? Please describe.**
_N/A_

**Describe the solution you'd like**
Since the JavaScript code used to detect gamepad inputs on the controller-side device uses a standard model, it should theoretically be usable on the host-side (where the virtual controller is running) to display the same information, no?

If this is the case, the same web page could be repurposed (or more likely expanded with some variable that selects the mode it is running in) in order to display the inputs being emulated.

This could help both with ensuring the connection is working properly, and with roughly testing the input delay.

**Describe alternatives you've considered**
Ideally, this should be accessible through the system tray menu. Two main ideas come to mind for how to deploy it:
1. One solution could be to have a dedicated HTML template for the host-side.
2. A "cleaner" alternative would be to have some sort of parameter (possibly a simple URL parameter?) that puts a single page in one of two modes: sender or receiver. In sender mode, the code includes the connection to the server; and in receiver mode, it only displays the gamepad inputs.

**Additional context**
_N/A_

**Comment by helloparthshah** [comment]
Currently opening the same webpage on the host-side should work for testing the controller as well as some websites such as https://gamepad-tester.com/ should be an option too.
